# Generated by Django 5.2.12 on 2026-06-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reclamo',
            new_name='reclamos_re_fecha_e_9f7993_idx',
            old_name='reclamos_re_fecha_e_idx',
        ),
        migrations.RenameIndex(
            model_name='reclamo',
            new_name='reclamos_re_estado_f7c28d_idx',
            old_name='reclamos_re_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='reclamo',
            new_name='reclamos_re_tema_56211c_idx',
            old_name='reclamos_re_tema_idx',
        ),
    ]
