# Generated by Django 5.2.12 on 2026-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(unique=True)),
                ('pagina_legacy_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID legacy de la Pagina contenedora (TarjetaSimplePage).', null=True)),
                ('titulo', models.TextField()),
                ('link_interno_legacy_id', models.PositiveIntegerField(blank=True, help_text='ID legacy de la Pagina destino para link interno.', null=True)),
                ('link_externo', models.CharField(blank=True, default='', max_length=500)),
                ('legacy_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarjeta simple',
                'verbose_name_plural': 'Tarjetas simples',
                'ordering': ['legacy_id'],
            },
        ),
    ]
