# Generated by Django 5.2.12 on 2026-06-09 00:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_tarjetasimple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordeonitem',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='acordeonpage',
            name='contenido_inferior',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='acordeonpage',
            name='contenido_superior',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
