# Generated by Django 5.2.12 on 2026-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sitio', models.CharField(default='DINAPI', max_length=255)),
                ('email_contacto', models.EmailField(default='contacto@dinapi.gov.py', max_length=254)),
                ('email_soporte', models.EmailField(default='soporte@dinapi.gov.py', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
