# Generated by Django 5.2.12 on 2026-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='parent_legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.CharField(choices=[('Page', 'Pagina'), ('HomePage', 'Home'), ('GeneralPage', 'General'), ('InstitucionalPage', 'Institucional'), ('ContactPage', 'Contacto'), ('NoticiaPage', 'Noticias'), ('RevistaPage', 'Revista'), ('BibliotecaPage', 'Biblioteca'), ('ConcursosPage', 'Concursos'), ('ReclamosPage', 'Reclamos'), ('ArchivoPage', 'Archivos'), ('AcordeonPage', 'Acordeon'), ('TarjetaPage', 'Tarjetas'), ('TarjetaSimplePage', 'Tarjetas Simples'), ('CalendarioPage', 'Calendario'), ('BoletinPage', 'Boletin'), ('BoletinMarcaPage', 'Boletin Marca'), ('PeriodoBoletinPage', 'Periodo Boletin'), ('PeriodoBoletinMarcaPage', 'Periodo Boletin Marca'), ('PeriodoBoletinMarcaGenericoPage', 'Periodo Boletin Marca Generico'), ('ProtegeLoTuyoPage', 'Protege lo Tuyo'), ('DiaPIPage', 'Dia PI'), ('CodepiNoticiaPage', 'Codepi Noticias'), ('GestorEnlacesPage', 'Gestor de Enlaces'), ('ArchivoDesplegablePage', 'Archivo Desplegable'), ('ConcursoJuventudPage', 'Concurso Juventud')], default='GeneralPage', max_length=80),
        ),
    ]
