# Generated by Django 5.2.12 on 2026-06-09 00:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_redes_sociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordeonPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Acordeón',
                'verbose_name_plural': 'Páginas — Acordeón (18)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ArchivoDesplegablePageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Archivo desplegable',
                'verbose_name_plural': 'Páginas — Archivos desplegables (8)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ArchivoPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Archivo',
                'verbose_name_plural': 'Páginas — Archivos (203)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='BoletinMarcaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Boletín Marca',
                'verbose_name_plural': 'Páginas — Boletines Marca (11)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='BoletinPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Boletín',
                'verbose_name_plural': 'Páginas — Boletines (4)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='CodepiNoticiaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Noticia CODEPI',
                'verbose_name_plural': 'Páginas — Noticias CODEPI (2)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ConcursoJuventudPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Concurso Juventud',
                'verbose_name_plural': 'Páginas — Concursos Juventud (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ConcursosPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Concursos',
                'verbose_name_plural': 'Páginas — Concursos (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='DiaPIPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Día PI (P2)',
                'verbose_name_plural': 'Páginas — Día PI (P2)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='GeneralPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — General',
                'verbose_name_plural': 'Páginas — Generales (67)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='GestorEnlacesPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Gestor de enlaces (P2)',
                'verbose_name_plural': 'Páginas — Gestor de enlaces (P2)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='HomePageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Home',
                'verbose_name_plural': 'Páginas — Home (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='InstitucionalPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Institucional',
                'verbose_name_plural': 'Páginas — Institucionales (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='NoticiaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Noticia',
                'verbose_name_plural': 'Páginas — Noticias (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='PageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Base',
                'verbose_name_plural': 'Páginas — Base (5)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='PeriodoBoletinMarcaGenericoPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Período Boletín Marca Genérico',
                'verbose_name_plural': 'Páginas — Períodos Boletín Marca Genérico (60)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='PeriodoBoletinMarcaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Período Boletín Marca',
                'verbose_name_plural': 'Páginas — Períodos Boletín Marca (76)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='PeriodoBoletinPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Período Boletín',
                'verbose_name_plural': 'Páginas — Períodos Boletín (33)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ProtegeLoTuyoPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Protege lo Tuyo (P2)',
                'verbose_name_plural': 'Páginas — Protege lo Tuyo (P2)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='ReclamosPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Reclamos',
                'verbose_name_plural': 'Páginas — Reclamos (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='RevistaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Revista',
                'verbose_name_plural': 'Páginas — Revistas (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='TarjetaPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Tarjeta',
                'verbose_name_plural': 'Páginas — Tarjetas (14)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.CreateModel(
            name='TarjetaSimplePageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Página — Tarjeta Simple',
                'verbose_name_plural': 'Páginas — Tarjetas Simples (1)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagina',),
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Configuracion del Sitio', 'verbose_name_plural': 'Configuracion del Sitio'},
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='url_consultas',
            field=models.URLField(blank=True, default='', help_text='URL del formulario de consultas/reclamos. Vacio = vista interna.', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='url_horarios',
            field=models.URLField(blank=True, default='', help_text='URL de la pagina de horarios de atencion (interna o externa).', max_length=500),
        ),
        migrations.AlterField(
            model_name='temaeje',
            name='pagina',
            field=models.ForeignKey(blank=True, help_text='Pagina interna a la que apunta este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_eje', to='core.pagina'),
        ),
        migrations.AlterField(
            model_name='temaeje',
            name='url_externa',
            field=models.URLField(blank=True, default='', help_text='URL externa de respaldo si no hay pagina interna asignada.', max_length=500),
        ),
    ]
