# Generated by Django 5.2.12 on 2026-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(unique=True)),
                ('pagina_legacy_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID legacy de la Pagina contenedora (mapea a core.Pagina.legacy_id).', null=True)),
                ('titulo', models.TextField()),
                ('link_externo', models.CharField(blank=True, default='', help_text='Si el archivo es un link externo en lugar de un PDF subido.', max_length=500)),
                ('pdf', models.FileField(blank=True, help_text='PDF subido. Vacio si es un link externo o si solo se conoce metadata.', null=True, upload_to='archivos/%Y/')),
                ('pdf_legacy_path', models.CharField(blank=True, default='', help_text='Ruta original del PDF en el assets/ legacy. Util para auditoria.', max_length=500)),
                ('fecha_ordenamiento', models.DateField(blank=True, null=True)),
                ('legacy_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archivo institucional',
                'verbose_name_plural': 'Archivos institucionales',
                'ordering': ['-fecha_ordenamiento', '-legacy_id'],
                'indexes': [models.Index(fields=['pagina_legacy_id'], name='archivos_ar_pagina__9ed4e7_idx')],
            },
        ),
    ]
