# Generated by Django 5.2.12 on 2026-06-09 00:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorianoticia',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contenido HTML de la noticia'),
        ),
        migrations.AlterField(
            model_name='revistapage',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
