# Generated by Django 5.2.12 on 2026-06-09 00:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actividad',
            new_name='calendario__fecha_i_262c41_idx',
            old_name='calendario__fecha_i_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='calendario__activo_503c1a_idx',
            old_name='calendario__activo_idx',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción'),
        ),
    ]
