# Generated by Django 5.2.12 on 2026-06-09 00:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_etiqueta_multimedia_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='enlaces_referencias',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='documentobiblioteca',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='imagenbiblioteca',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='videobiblioteca',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
