# Generated by Django 5.2.12 on 2026-06-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor numero = aparece primero.')),
                ('pagina_destino_legacy_id', models.PositiveIntegerField(blank=True, help_text='legacy_id de la Pagina destino (resuelve la URL dinamicamente).', null=True)),
                ('link_interno_url', models.CharField(blank=True, default='', help_text='URL interna explicita (alternativa a pagina_destino_legacy_id).', max_length=500)),
                ('link_externo', models.CharField(blank=True, default='', help_text='URL externa absoluta. Si esta poblada, prevalece sobre las internas.', max_length=500)),
                ('target_blank', models.BooleanField(default=False, help_text='Abrir en pestana nueva. Recomendado para link externo.')),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, help_text='Si tiene padre, este item aparece como sub-item del desplegable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='menus.menuprincipal')),
            ],
            options={
                'verbose_name': 'Item del menu principal',
                'verbose_name_plural': 'Menu principal (curado)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
